name: .NET

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  
jobs:
  build:
    runs-on: windows-latest
    
    steps:
    
    - name: Generate current date
      id: date
      run: echo "::set-output name=date::$(date +%Y%m%d%H%M)"
      
    - name: Generate Output Path 
      id: output_path
      run: echo "::set-output name=OUTPUTPATH::C:\\actions-runner\\_work\\build_output\\${{github.ref_name}}\\artifacts\\${{steps.date.outputs.date}}.${{github.run_id}}.${{github.run_number}}.${{github.run_attempt}}"
      
    - name: Show Env ${{github.ref_name}}
      run: echo ${{env.BUILD_NUMBER}}
      
    - name: Output PATH
      run: echo ${{ steps.output_path.outputs.OUTPUTPATH }}
      
