name: .NET

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
    
env:
  BUILD_NUMBER: ${{ github.event.repository.updated_at}}.${{github.run_id}}.${{github.run_number}}.${{github.run_attempt}}

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Show Env ${GITHUB_REF#refs/*/} 
      run: env
  
