name: .NET

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
env:
  BUILD_NUMBER: ${{github.run_id}}.${{github.run_number}}.${{github.run_attempt}}
  
jobs:
  build:
    runs-on: windows-2019
    
    steps:
    - name: Test ${{(Get-Date -format 'yyyy-MM-dd-HH-mm')}}
      run: echo "Test ${{Get-Date -format 'yyyy-MM-dd-HH-mm'}}"
    
      
