name: .NET

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
env:
  BUILD_NUMBER: ${{github.run_id}}.${{github.run_number}}.${{github.run_attempt}}
  
jobs:
  build:
    runs-on: windows-2019
    
    steps:
    - name: Test 
      run: |
        echo "Powershell Module Path ${{env.PSModulePath}}"
        if (Test-Path -Path "${{env.PSModulePath}}") { "PSModulePath exists in PATH!" } else { $env:Path += ";${{env.PSModulePath}}" }
        if (Test-Path -Path "${{env.PSModulePath}}") { "PSModulePath exists in PATH!" } else { "Does not exist" }
        Get-Date -format 'yyyy-MM-dd-HH-mm'
        
      
    
    
      
