name: .NET

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
env:
  BUILD_NUMBER: ${{github.run_id}}.${{github.run_number}}.${{github.run_attempt}}
  PS_MODULE_PATH: "C:\\Program Files\\WindowsPowerShell\\Modules"
  
jobs:
  build:
    runs-on: windows-2019
    
    steps:
    - name: Test 
      id: date
      run: |
        echo "Powershell Module Path ${{env.PS_MODULE_PATH}}"
        if (Test-Path -Path "${{env.PS_MODULE_PATH}}") { "PSModulePath exists in PATH!" } else { $env:Path += ";${{env.PS_MODULE_PATH}}" }
        if (Test-Path -Path "${{env.PS_MODULE_PATH}}") { "PSModulePath exists in PATH!" } else { "Does not exist" }
        echo "::set-output name=date::${{Get-Date -format 'yyyy-MM-dd-HH-mm'}}"
        echo 'CURRENT_DT="${{Get-Date -format 'yyyy-MM-dd-HH-mm'}}"' >> $GITHUB_ENV
        echo "${{env.CURRENT_DT}}"
        echo "${{steps.date.outputs.date}}
    - name: Show Current Date 
      run: echo "${{env.CURRENT_DT}}"
    
        
      
    
    
      
