name: .NET

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
env:
  BUILD_NUMBER: ${{github.run_id}}.${{github.run_number}}.${{github.run_attempt}}
  
jobs:
  build:
    runs-on: windows-latest
    
    steps:
    
    - name: Generate current date
      id: date
      run: echo 'CURRENT_DT=${{(Get-Date -format "yyyy")}}-${{(Get-Date -format "MM")}}-${{(Get-Date -format "dd")}}-${{(Get-Date -format "HH")}}-${{(Get-Date -format "mm")}}' >> $GITHUB_ENV
      
    - name: Generate Output Path 
      id: output_path
      run: echo "OUTPUTPATH=C:\\actions-runner\\_work\\build_output\\${{github.ref_name}}\\artifacts\\${{env.CURRENT_DT}}.${{env.BUILD_NUMBER}}" >> $GITHUB_ENV
      
    - name: Show Env ${{github.ref_name}}
      run: 'echo ${{env.BUILD_NUMBER}} '
      
    - name: Output PATH
      run: echo ${{ env.OUTPUTPATH }}
      
