name: .NET

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
    
env:
  BUILD_NUMBER: $(date +'%Y-%m-%d').${{github.run_id}}.${{github.run_number}}.${{github.run_attempt}}
#   OUTPUT_PATH: "C:\\actions-runner\\_work\build_output\\${{github.ref_name}}\\artifacts\\${{BUILD_NUMBER}}"
  
jobs:
  build:
    runs-on: windows-latest
    steps:
    
    - name: Generate current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      
    - name: Show Env ${{github.ref_name}}
      run: echo ${{env.BUILD_NUMBER}}
      
    - name: Output PATH
      run: echo ${{ steps.date.outputs.date }}
  
