name: .NET

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
env:
  BUILD_NUMBER: ${{github.run_id}}.${{github.run_number}}.${{github.run_attempt}}
  
jobs:
  build:
    runs-on: windows-latest
    
    steps:
    
    - name: Generate current date
      id: date
      run: echo '::set-output name=date::(Get-Date -format "yyyy") + "-" + (Get-Date -format "MM") + "-" +  (Get-Date -format "dd") + "-" +  (Get-Date -format "HH") + "-" +  (Get-Date -format "mm")'
      
    - name: Generate Output Path 
      id: output_path
      run: echo "::set-output name=OUTPUTPATH::C:\\actions-runner\\_work\\build_output\\${{github.ref_name}}\\artifacts\\${{steps.date.outputs.date}}.${{env.BUILD_NUMBER}}"
      
    - name: Show Env ${{github.ref_name}}
      run: 'echo ${{env.BUILD_NUMBER}} '
      
    - name: Output PATH
      run: echo ${{ steps.output_path.outputs.OUTPUTPATH }}
      
