name: .NET

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
    
env:
  BUILD_NUMBER: ${{ github.event.repository.updated_at}}.${{github.run_id}}.${{github.run_number}}.${{github.run_attempt}}
  OUTPUT_PATH: "C:\\actions-runner\\_work\build_output\\${{github.ref_name}}\\artifacts\\${{BUILD_NUMBER}}"

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Generate current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Show Env ${{github.ref_name}}
      run: env
    - name: Output PATH
      run: echo ${{ steps.date.outputs.date }}
  
