name: .NET

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
env:
  BUILD_NUMBER: ${{github.run_id}}.${{github.run_number}}.${{github.run_attempt}}
  
jobs:
  build:
    runs-on: windows-2019
    
    steps:
    - name: Test 
      run: |
        ${{env.PSModulePath}}
        Get-Module -ListAvailable
        "C:\\program files\\powershell\\7\\Modules\\Get-Date -format 'yyyy-MM-dd-HH-mm'" 
        
      
    
    
      
